# Generated by Django 4.2 on 2023-04-26 12:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reviews", "0001_add_cat_genre_title_model"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Genre",
            new_name="Genres",
        ),
        migrations.RenameModel(
            old_name="Title",
            new_name="Titles",
        ),
    ]
